%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-ros2nodl
Version:        2.0.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ros2nodl package

License:        Apache-2.0
URL:            https://index.ros.org/p/ros2nodl/#kilted
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-ament-index-python
Requires:       ros-kilted-nodl-conformance
Requires:       ros-kilted-nodl-observe
Requires:       ros-kilted-nodl-schema
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-ros2cli
Requires:       ros-kilted-rosgraph-msgs
Requires:       ros-kilted-rosidl-runtime-py
Requires:       ros-kilted-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-kilted-ament-index-python
BuildRequires:  ros-kilted-nodl-conformance
BuildRequires:  ros-kilted-nodl-observe
BuildRequires:  ros-kilted-nodl-schema
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ros2cli
BuildRequires:  ros-kilted-rosgraph-msgs
BuildRequires:  ros-kilted-rosidl-runtime-py
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-builtin-interfaces
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-std-msgs
%endif

%description
ros2cli command entrypoint for NoDL.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/kilted"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Fri Sep 04 2026 ROSGraph Working Group <rosgraph-wg@googlegroups.com> - 2.0.2-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Ubuntu Robotics <ubuntu-robotics@lists.launchpad.net> - 0.3.1-5
- Autogenerated by Bloom

* Wed Mar 06 2024 Ubuntu Robotics <ubuntu-robotics@lists.launchpad.net> - 0.3.1-4
- Autogenerated by Bloom

