%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-nodl-observe
Version:        2.0.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS nodl_observe package

License:        Apache-2.0
URL:            https://index.ros.org/p/nodl_observe/#kilted
Source0:        %{name}-%{version}.tar.gz

Requires:       cli11-devel
Requires:       ros-kilted-builtin-interfaces
Requires:       ros-kilted-rcl-action
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rosgraph-msgs
Requires:       ros-kilted-ros-workspace
BuildRequires:  cli11-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-auto
BuildRequires:  ros-kilted-builtin-interfaces
BuildRequires:  ros-kilted-rcl-action
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-rosgraph-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-cmake-pytest
BuildRequires:  ros-kilted-example-interfaces
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-rmw-cyclonedds-cpp
BuildRequires:  ros-kilted-rmw-fastrtps-cpp
BuildRequires:  ros-kilted-rmw-implementation-cmake
BuildRequires:  ros-kilted-rmw-zenoh-cpp
BuildRequires:  ros-kilted-rosidl-runtime-py
BuildRequires:  ros-kilted-std-msgs
%endif

%description
Observe a running ROS node and produce its runtime description as a
rosgraph_msgs/Node message.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Fri Sep 04 2026 ROSGraph Working Group <rosgraph-wg@googlegroups.com> - 2.0.2-1
- Autogenerated by Bloom

