<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nodl_observe</name>
  <version>2.0.2</version>
  <description>Observe a running ROS node and produce its runtime description as a rosgraph_msgs/Node message.</description>
  <maintainer email="rosgraph-wg@googlegroups.com">ROSGraph Working Group</maintainer>
  <license>Apache-2.0</license>
  <author email="sylukewicent@gmail.com">Luke Sy</author>
  <author email="hello@alistairenglish.com">Alistair English</author>
  <author email="me@emersonknapp.com">Emerson Knapp</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>
  <buildtool_depend>ros_environment</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rcl_action</depend>
  <depend>rosgraph_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>builtin_interfaces</depend>
  <depend>rmw</depend>
  <depend>cli11</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>rmw_implementation_cmake</test_depend>
  <test_depend>rmw_fastrtps_cpp</test_depend>
  <test_depend>rmw_cyclonedds_cpp</test_depend>
  <test_depend condition="$ROS_DISTRO != 'humble'">rmw_zenoh_cpp</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>rclpy</test_depend>
  <test_depend>rosidl_runtime_py</test_depend>
  <test_depend>std_msgs</test_depend>
  <test_depend>example_interfaces</test_depend>
  <test_depend condition="$ENABLE_PIP_TEST_DEPENDS == 1">mcap-ros2-support</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
