# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
# generated by datamodel-codegen:
#   filename:  nodl.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

try:
    from pydantic.v1 import BaseModel, Extra, Field, conint, constr
except ImportError:
    from pydantic import BaseModel, Extra, Field, conint, constr


class ScalarType(Enum):
    """
    Scalar types:
    - ``bool``: C++ ``bool``, Python ``bool``
    - ``int``: C++ ``int64_t``, Python ``int``
    - ``double``: C++ ``double``, Python ``float``
    - ``string``: C++ ``std::string``, Python ``str``
    - ``none``: No code generated (used for structure-only nodes)

    """

    bool = 'bool'
    int = 'int'
    double = 'double'
    string = 'string'
    none = 'none'


class ArrayType(Enum):
    """
    Array types:
    - ``bool_array``: C++ ``std::vector<bool>``, Python ``[bool]``
    - ``byte_array``: Sequence of byte integers (``0`` through ``255``)
    - ``int_array``: C++ ``std::vector<int64_t>``, Python ``[int]``
    - ``double_array``: C++ ``std::vector<double>``, Python ``[float]``
    - ``string_array``: C++ ``std::vector<std::string>``, Python ``[str]``

    """

    bool_array = 'bool_array'
    byte_array = 'byte_array'
    int_array = 'int_array'
    double_array = 'double_array'
    string_array = 'string_array'


class Reference(BaseModel):
    """
    A reference to another NoDL document.
    """

    class Config:
        extra = Extra.forbid

    ref: constr(regex=r'^[a-z][a-z0-9+.-]*://[^\s/][^\s]*$') = Field(
        ...,
        description='Reference to a NoDL document, as a ``<scheme>://<body>`` URI.\nDynamically egistered resolvers handle these URIs, so the schema does not restrict them.\nThese resolver schemes are built in:\n``nodl://<package>/<name>`` fetches from the ament index.\n``local://<relative path to file>`` is another document in the same package, as a relative path.\n',
        examples=['nodl://sensor_common/imu_driver'],
    )


class History(Enum):
    """
    History policy.
    """

    KEEP_LAST = 'KEEP_LAST'
    KEEP_ALL = 'KEEP_ALL'
    SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'


class Reliability(Enum):
    """
    Reliability policy.
    """

    RELIABLE = 'RELIABLE'
    BEST_EFFORT = 'BEST_EFFORT'
    SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'
    BEST_AVAILABLE = 'BEST_AVAILABLE'


class Durability(Enum):
    """
    Durability policy.
    """

    TRANSIENT_LOCAL = 'TRANSIENT_LOCAL'
    VOLATILE = 'VOLATILE'
    SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'
    BEST_AVAILABLE = 'BEST_AVAILABLE'


class Liveliness(Enum):
    """
    Liveliness policy.
    """

    AUTOMATIC = 'AUTOMATIC'
    MANUAL_BY_TOPIC = 'MANUAL_BY_TOPIC'
    SYSTEM_DEFAULT = 'SYSTEM_DEFAULT'
    BEST_AVAILABLE = 'BEST_AVAILABLE'


class QosProfile(BaseModel):
    """
    QoS profile settings. Mirrors ``rcl_interfaces/QoSProfile`` field
    set and naming, but uses string enums in place of ``RMW`` integer
    codes for readability and signed-int nanoseconds in place of
    ``builtin_interfaces/Duration`` for ergonomics -- codegen converts
    the int to a ``Duration``. ``UNKNOWN`` values from the ``RMW`` spec are
    excluded; they are only meaningful for runtime observation.

    """

    class Config:
        extra = Extra.forbid

    history: History = Field(..., description='History policy.')
    depth: Optional[conint(ge=1)] = Field(None, description='Queue depth. Required when ``history`` is ``KEEP_LAST``.')
    reliability: Reliability = Field(..., description='Reliability policy.')
    durability: Optional[Durability] = Field(None, description='Durability policy.')
    deadline_ns: Optional[conint(ge=0)] = Field(
        None,
        description='Deadline between successive messages, in nanoseconds.\nZero means no deadline is enforced. Stored as a signed\n64-bit integer (~292 years range).\n',
    )
    lifespan_ns: Optional[conint(ge=0)] = Field(
        None,
        description='Maximum age of a message before it is dropped, in\nnanoseconds. Zero means messages never expire.\n',
    )
    liveliness: Optional[Liveliness] = Field(None, description='Liveliness policy.')
    liveliness_lease_duration_ns: Optional[conint(ge=0)] = Field(
        None,
        description='Maximum time between liveliness assertions before the\npublisher is considered not alive, in nanoseconds. Zero\nmeans the lease never expires.\n',
    )


class TopicEndpoint(BaseModel):
    """
    Topic endpoint -- same shape for publishers and subscriptions;
    direction is implied by which top-level array contains it.

    """

    class Config:
        extra = Extra.forbid

    name: constr(regex=r'^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$') = Field(..., description='Topic name.')
    type: constr(regex=r'^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$') = Field(
        ...,
        description='ROS interface type, format ``package/(msg|srv|action)?/TypeName``.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies ``msg``).\n',
        examples=[
            'std_msgs/msg/String',
            'std_msgs/String',
            'geometry_msgs/msg/Twist',
            'std_srvs/srv/Trigger',
            'lifecycle_msgs/srv/ChangeState',
            'example_interfaces/action/Fibonacci',
            'nav2_msgs/action/NavigateToPose',
        ],
    )
    qos: QosProfile
    description: Optional[str] = None


class ServiceEndpoint(BaseModel):
    """
    Service endpoint -- same shape for servers and clients;
    direction is implied by which top-level array contains it.
    A single qos profile applies; ``create_service`` accepts only one
    QoS input and applies it to both the request and response
    sides at runtime.

    """

    class Config:
        extra = Extra.forbid

    name: constr(regex=r'^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$') = Field(..., description='Service name.')
    type: constr(regex=r'^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$') = Field(
        ...,
        description='ROS interface type, format ``package/(msg|srv|action)?/TypeName``.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies ``msg``).\n',
        examples=[
            'std_msgs/msg/String',
            'std_msgs/String',
            'geometry_msgs/msg/Twist',
            'std_srvs/srv/Trigger',
            'lifecycle_msgs/srv/ChangeState',
            'example_interfaces/action/Fibonacci',
            'nav2_msgs/action/NavigateToPose',
        ],
    )
    qos: Optional[QosProfile] = None
    description: Optional[str] = None


class ActionEndpoint(BaseModel):
    """
    Action endpoint -- same shape for servers and clients;
    direction is implied by which top-level array contains it.
    The underlying decomposition into goal/result/cancel services
    and feedback/status topics (per ``rcl_interfaces/Action``) is not
    modelled here; it is an implementation concern.

    """

    class Config:
        extra = Extra.forbid

    name: constr(regex=r'^[A-Za-z]$|^[/~A-Za-z][A-Za-z0-9_/]*[A-Za-z0-9_]$') = Field(..., description='Action name.')
    type: constr(regex=r'^[a-zA-Z][a-zA-Z0-9_]*(/(msg|srv|action))?/[A-Z][a-zA-Z0-9]*$') = Field(
        ...,
        description='ROS interface type, format ``package/(msg|srv|action)?/TypeName``.\nMiddle namespace is optional and may be determined by usage\ncontext (e.g. a publisher type implies ``msg``).\n',
        examples=[
            'std_msgs/msg/String',
            'std_msgs/String',
            'geometry_msgs/msg/Twist',
            'std_srvs/srv/Trigger',
            'lifecycle_msgs/srv/ChangeState',
            'example_interfaces/action/Fibonacci',
            'nav2_msgs/action/NavigateToPose',
        ],
    )
    description: Optional[str] = None


class Validation(BaseModel):
    """
    Dictionary of validation function names and their arguments.
    Validators can be specified with or without the ``<>`` suffix (both are equivalent).
    For example: ``bounds<>: [0, 100]`` is the same as ``bounds: [0, 100]``

    """

    class Config:
        extra = Extra.forbid

    bounds__: Optional[list[float]] = Field(
        None,
        alias='bounds<>',
        description='Inclusive bounds checking: ``[lower, upper]``',
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lt__: Optional[Union[list[float], float]] = Field(
        None,
        alias='lt<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt__: Optional[Union[list[float], float]] = Field(
        None,
        alias='gt<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    lt_eq__: Optional[Union[list[float], float]] = Field(
        None,
        alias='lt_eq<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt_eq__: Optional[Union[list[float], float]] = Field(
        None,
        alias='gt_eq<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    one_of__: Optional[list[list]] = Field(
        None,
        alias='one_of<>',
        description='Parameter must be one of the specified values: ``[[val1, val2, ...]]``',
        examples=[[['spline', 'linear']], [[0, 1, 2, -1]], [[True, False]]],
    )
    bounds: Optional[list[float]] = Field(
        None,
        description='Inclusive bounds checking: ``[lower, upper]``',
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lt: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    lt_eq: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    gt_eq: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    one_of: Optional[list[list]] = Field(
        None,
        description='Parameter must be one of the specified values: ``[[val1, val2, ...]]``',
        examples=[[['spline', 'linear']], [[0, 1, 2, -1]], [[True, False]]],
    )
    not_empty__: Optional[list] = Field(
        None,
        alias='not_empty<>',
        description='Validator that takes no arguments',
        examples=[None, []],
    )
    not_empty: Optional[list] = Field(None, description='Validator that takes no arguments', examples=[None, []])
    fixed_size__: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        alias='fixed_size<>',
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    size_gt__: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        alias='size_gt<>',
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    size_lt__: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        alias='size_lt<>',
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    fixed_size: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    size_gt: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    size_lt: Optional[Union[list[conint(ge=0)], conint(ge=0)]] = Field(
        None,
        description='Size/length constraint: ``[length]``',
        examples=[[6], [10], 6],
    )
    unique__: Optional[list] = Field(
        None,
        alias='unique<>',
        description='Validator that takes no arguments',
        examples=[None, []],
    )
    subset_of__: Optional[list[list]] = Field(
        None,
        alias='subset_of<>',
        description='All array elements must be in the specified set: ``[[val1, val2, ...]]``',
        examples=[[['x', 'y', 'z']], [[1, 2, 3, 4, 5]]],
    )
    element_bounds__: Optional[list[float]] = Field(
        None,
        alias='element_bounds<>',
        description='Inclusive bounds checking: ``[lower, upper]``',
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lower_element_bounds__: Optional[Union[list[float], float]] = Field(
        None,
        alias='lower_element_bounds<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    upper_element_bounds__: Optional[Union[list[float], float]] = Field(
        None,
        alias='upper_element_bounds<>',
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    unique: Optional[list] = Field(None, description='Validator that takes no arguments', examples=[None, []])
    subset_of: Optional[list[list]] = Field(
        None,
        description='All array elements must be in the specified set: ``[[val1, val2, ...]]``',
        examples=[[['x', 'y', 'z']], [[1, 2, 3, 4, 5]]],
    )
    element_bounds: Optional[list[float]] = Field(
        None,
        description='Inclusive bounds checking: ``[lower, upper]``',
        examples=[[0, 100], [0.0, 1.0], [-1.0, 1.0]],
    )
    lower_element_bounds: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )
    upper_element_bounds: Optional[Union[list[float], float]] = Field(
        None,
        description='Single value comparison: ``[value]`` or bare value',
        examples=[[0], [100], [0.001], 15, 0.5],
    )


class ParameterDefinition(BaseModel):
    class Config:
        extra = Extra.forbid

    type: Union[
        ScalarType,
        ArrayType,
        constr(
            regex=r'^(string_fixed_[1-9][0-9]*|int_array_fixed_[1-9][0-9]*|double_array_fixed_[1-9][0-9]*|string_array_fixed_[1-9][0-9]*)$'
        ),
    ] = Field(..., description='The parameter data type')
    default_value: Optional[Any] = Field(
        None,
        description='Initial value for the parameter. Type must match the declared parameter type.\nIf omitted, the parameter becomes required at initialization.\nSupports: ``bool``, ``int``, ``double`` (including ``NaN``, ``Inf``, scientific notation), ``string``,\nand arrays of these types. A ``byte_array`` default is a sequence of\ninteger byte values from ``0`` through ``255``.\n',
    )
    description: Optional[str] = Field(
        '',
        description='Human-readable description displayed by ``ros2 param describe``',
    )
    read_only: Optional[bool] = Field(
        False,
        description='If true, parameter can only be set at launch, not dynamically',
    )
    additional_constraints: Optional[str] = Field(
        '',
        description='Custom constraint metadata (e.g., JSON schema) - not validated by the library',
    )
    validation: Optional[Validation] = None


class NodlDocument(BaseModel):
    """
    NoDL (Node Definition Language) v2 schema.

    Describes the public ROS interface of a single ROS 2 node:
    parameters, publishers, subscriptions, service servers/clients,
    and action servers/clients. Field names align with ``rcl_interfaces``
    and ``rosgraph_msgs`` (``Topic``, ``Service``, ``Action``) so a NoDL document
    maps cleanly onto runtime introspection types.

    Node identity (name, package, namespace) is established by the
    enclosing package and the file's location within it, not declared
    inside the document.

    """

    class Config:
        extra = Extra.forbid

    nodl_version: int = Field(2, const=True, description='NoDL schema major version this document targets.')
    description: Optional[str] = Field(None, description='Human-readable description of what this node does.')
    codegen: Optional[dict[str, dict[str, Any]]] = Field(
        None,
        description='Opaque metadata for code generation tools, keyed by target language or tool\n(e.g. ``cpp``, ``python``). Each value is an object whose contents are\ntool-defined. The NoDL schema does not constrain them.\n',
    )
    include: Optional[list[Reference]] = Field(
        None,
        description='Other NoDL documents whose interface entities are merged into this one.\nEach reference is resolved - recursively, following all references until done.\nCircular inclusion is an error.\nAn entity-name collision (for example two publishers named ``/status``) is an error.\n',
    )
    parameters: Optional[dict[str, ParameterDefinition]] = Field(
        None,
        description='ROS parameters declared by this node, keyed by parameter name.\nParameter shape is borrowed from ``generate_parameter_library``\n(see ``parameter.schema.yaml``).\n',
    )
    publishers: Optional[list[TopicEndpoint]] = Field(None, description='Topic publishers exposed by this node.')
    subscriptions: Optional[list[TopicEndpoint]] = Field(None, description='Topic subscriptions consumed by this node.')
    service_servers: Optional[list[ServiceEndpoint]] = Field(None, description='Service servers exposed by this node.')
    service_clients: Optional[list[ServiceEndpoint]] = Field(None, description='Service clients used by this node.')
    action_servers: Optional[list[ActionEndpoint]] = Field(None, description='Action servers exposed by this node.')
    action_clients: Optional[list[ActionEndpoint]] = Field(None, description='Action clients used by this node.')
