# Auto-generated by nodl_generator_cpp --cmake-deps
# Do not edit.
set(my_node_NODL_SOURCES
  /RESOLVED/input.nodl.yaml
  /RESOLVED/1.nodl.yaml
)
set(my_node_ROS_DEPS
  example_interfaces
  geometry_msgs
  nav2_msgs
  rclcpp
  rclcpp_action
  std_msgs
  std_srvs
)
set(my_node_GENERATED_FILES
  my_node.hpp
  my_node.cpp
  my_node_parameters.yaml
  my_node_parameters.hpp
)
