# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
"""Pure helpers for emitting CMake dependency information.

Used by :func:`generate.cmake_deps` and the CLI ``--cmake-deps`` path.
"""

from __future__ import annotations

from pathlib import Path

from nodl_generator_cpp.models import CodegenCpp
from nodl_schema.models import ActionEndpoint, ServiceEndpoint, TopicEndpoint


def _package_from_header(header: str) -> str:
    """Extract the ROS package name from a C++ header path.

    >>> _package_from_header('rclcpp/rclcpp.hpp')
    'rclcpp'
    >>> _package_from_header('rclcpp_lifecycle/lifecycle_node.hpp')
    'rclcpp_lifecycle'
    """
    return header.split('/')[0]


def _package_from_type(ros_type: str) -> str:
    """Extract the ROS package name from a ROS interface type.

    >>> _package_from_type('std_msgs/msg/String')
    'std_msgs'
    >>> _package_from_type('geometry_msgs/msg/Twist')
    'geometry_msgs'
    """
    return ros_type.split('/')[0]


def ros_deps(
    barriers: list[CodegenCpp],
    publishers: list[TopicEndpoint],
    subscriptions: list[TopicEndpoint],
    service_servers: list[ServiceEndpoint],
    service_clients: list[ServiceEndpoint],
    action_servers: list[ActionEndpoint],
    action_clients: list[ActionEndpoint],
) -> list[str]:
    """Compute the sorted, deduplicated list of ROS package dependencies.

    Sources:

    - Every barrier with a ``header`` field contributes its package
      (part before first ``/``).
    - Every filtered entity contributes its message/service/action package
      (part before first ``/`` of its ``type``).
    - If any action servers or action clients are present, ``rclcpp_action``
      is added (the generated code includes ``rclcpp_action/rclcpp_action.hpp``).
    """
    pkgs: set[str] = set()

    for barrier in barriers:
        if barrier.header is not None:
            pkgs.add(_package_from_header(barrier.header))

    all_entities: list[TopicEndpoint | ServiceEndpoint | ActionEndpoint] = [
        *publishers,
        *subscriptions,
        *service_servers,
        *service_clients,
        *action_servers,
        *action_clients,
    ]
    for entity in all_entities:
        pkgs.add(_package_from_type(entity.type))

    if action_servers or action_clients:
        pkgs.add('rclcpp_action')

    return sorted(pkgs)


def generated_filenames(target_name: str, has_parameters: bool) -> list[str]:
    """Return the list of filenames the generator will produce.

    Always includes ``<target>.hpp`` and ``<target>.cpp``.
    When *has_parameters* is true, also includes
    ``<target>_parameters.yaml`` and ``<target>_parameters.hpp``.
    """
    filenames = [f'{target_name}.hpp', f'{target_name}.cpp']
    if has_parameters:
        filenames.append(f'{target_name}_parameters.yaml')
        filenames.append(f'{target_name}_parameters.hpp')
    return filenames


def format_cmake_deps(
    target: str,
    sources: list[Path],
    ros_deps: list[str],
    generated: list[str],
) -> str:
    """Format the contents of a ``<target>_deps.cmake`` file.

    Returns a string ready to be written to disk.
    """
    lines = [
        '# Auto-generated by nodl_generator_cpp --cmake-deps',
        '# Do not edit.',
    ]

    lines.append(f'set({target}_NODL_SOURCES')
    for src in sources:
        lines.append(f'  {src}')
    lines.append(')')

    lines.append(f'set({target}_ROS_DEPS')
    for dep in ros_deps:
        lines.append(f'  {dep}')
    lines.append(')')

    lines.append(f'set({target}_GENERATED_FILES')
    for gen in generated:
        lines.append(f'  {gen}')
    lines.append(')')

    return '\n'.join(lines) + '\n'
