# SPDX-FileCopyrightText: 2026 Open Source Robotics Foundation, Inc.
# SPDX-License-Identifier: Apache-2.0
# generated by datamodel-codegen:
#   filename:  codegen_cpp.schema.yaml

from __future__ import annotations

from enum import Enum
from typing import Optional

try:
    from pydantic.v1 import BaseModel, Extra, Field, constr
except ImportError:
    from pydantic import BaseModel, Extra, Field, constr


class Role(Enum):
    """
    How this document's implementation participates in the
    generated class.  Currently only ``BASE_CLASS`` is supported.

    """

    BASE_CLASS = 'BASE_CLASS'


class CodegenCpp(BaseModel):
    """
    Schema for the ``codegen.cpp`` object in NoDL documents.
    Validated by ``nodl_generator_cpp``, not ``nodl_schema``.

    """

    class Config:
        extra = Extra.forbid

    role: Role = Field(
        ...,
        description="How this document's implementation participates in the\ngenerated class.  Currently only ``BASE_CLASS`` is supported.\n",
    )
    class_: Optional[constr(regex=r'^[A-Za-z_][A-Za-z0-9_:]*$')] = Field(
        None,
        alias='class',
        description='Fully-qualified C++ class name to inherit from\n(e.g. ``rclcpp::Node``).\n',
    )
    header: Optional[str] = Field(
        None,
        description='C++ header to ``#include`` for the base class\n(e.g. ``rclcpp/rclcpp.hpp``).\n',
    )
